//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBikesWebpage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
        }

        
        public int ProductID { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string ProductNumber { get; set; }

        [DisplayFormat(NullDisplayText = "-")]
        [Required]
        public string Color { get; set; }

        [Required]
        [DisplayFormat(NullDisplayText = "-", DataFormatString = "{0:C}")]
        [Range(0, Int64.MaxValue, ErrorMessage = "Minimum standard cost is 0.")]
        public decimal StandardCost { get; set; }

        [Required]
        [DisplayFormat(NullDisplayText = "-",DataFormatString = "{0:C}") ]
        [Range(0, Int64.MaxValue, ErrorMessage = "Minimum list price is 0.")]        
        public decimal ListPrice { get; set; }

        [Required]
        [DisplayFormat(NullDisplayText = "-")]
        [Range(0, Int64.MaxValue, ErrorMessage = "Minimum size is 0.")] 
        public string Size { get; set; }

        [DisplayFormat(NullDisplayText = "-")]
        [Range(0, Int64.MaxValue, ErrorMessage = "Minimum weight is 0.")]
        public Nullable<decimal> Weight { get; set; }

        public Nullable<int> ProductCategoryID { get; set; }

        public Nullable<int> ProductModelID { get; set; }

        public System.DateTime SellStartDate { get; set; }

        [DisplayFormat(NullDisplayText = "-")]
        public Nullable<System.DateTime> SellEndDate { get; set; }

        [DisplayFormat(NullDisplayText = "-")]
        public Nullable<System.DateTime> DiscontinuedDate { get; set; }

        [DisplayFormat(NullDisplayText = "-")]
        [ScaffoldColumn(false)] 
        public byte[] ThumbNailPhoto { get; set; }

        [DisplayFormat(NullDisplayText = "-")]
        public string ThumbnailPhotoFileName { get; set; }

        public System.Guid rowguid { get; set; }

        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }

        public virtual ProductModel ProductModel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }

    }
}
